# Generated by Django 4.1.3 on 2023-01-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('card_cvv', models.IntegerField()),
                ('total_value', models.IntegerField()),
                ('extra_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
