# Generated by Django 4.1 on 2023-01-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comission_value',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
