# Generated by Django 4.1 on 2023-01-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_payment_comission_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comission_value',
            field=models.IntegerField(),
        ),
    ]
