# Generated by Django 4.1 on 2023-01-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
