# Generated by Django 4.1 on 2023-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comission_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
