# Generated by Django 4.1 on 2023-01-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_payment_comission_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comission_value',
            field=models.FloatField(auto_created=True, blank=True, null=True),
        ),
    ]
